### ISSUE TITLE
golang generated server should use https://github.com/kataras/iris

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/go-raml#161]
also check
- oauth 2 is done
- https is done
- UI for rest exploration is inside
- good example

**Comment by zaibon** [comment]
Woth reading this before going to that path:
http://www.florinpatan.ro/2016/10/why-you-should-not-use-iris-for-your-go.html

**Comment by iwanbk** [comment]
```
http://www.florinpatan.ro/2016/10/why-you-should-not-use-iris-for-your-go.html
```
Wow, this iris project has problems:
-  license issue by stealing `httprouter` code 
- single contributor. There should be other contributors, but the author removes the contributions history from git

i think we shouldn't use it.

**Comment by delandtj** [comment]
I second that

**Comment by despiegk** [comment]
which framework do we use today?

**Comment by despiegk** [comment]
how are we from feature perspective? see body of issue.

**Comment by iwanbk** [comment]
```
which framework do we use today?
```
we don't use any framework. What we use today:
- gorilla/mux for the router
- go-validator to validate request body
- justinas/alice for middleware chaining

```
how are we from feature perspective? see body of issue.
```
- oauth2 is done, but not ready to be used. It also doesn't have ready to use plugin for popular oauth2 provider like twitter, facebook, and google.

- no https
Because RAML standard doesn't have enough spec to generate ready to use HTTPS server.
But of course we can define our own spec

- UI for REST API docs is done

- i think the example is quite good.

**Comment by despiegk** [comment]
Should integrate with its itsyou.online soon and with example

**Comment by iwanbk** [comment]
```
Should integrate with its itsyou.online soon and with example
```
we already have the example.
We can't generate ready-to-use integration because of limitation in the info from .raml file
