### ISSUE TITLE
generated python client doesn't encode json

### ISSUE THREAD

**Issue by LeeSmet** [Jumpscale/go-raml#170]
After generating and testing the client for itsyou.online, it appears that data send as the body of a post or put request isn't encoded as json.

**Comment by iwanbk** [comment]
@LeeSmet yes, it is an expected behaviour of current implementation.
User needs to encode it as json using `json.dump`, example : https://github.com/g8os/zerotier_client/blob/master/example.py#L24.

The reason it doesn't encode: client might have python `class` instead of `json` object.

But i think it is better for the client lib to do the encoding, make it consistent with Go & Nim code.

what do you think @robvanmieghem ?

**Comment by robvanmieghem** [comment]
@iwanbk Can't we do both? Check if the type is a string and if not, encode is as json?
Simply encoding everything we get would wrap a string in quotes again:
```
In [1]: import json

In [2]: json.dumps('test')
Out[2]: '"test"'
```

**Comment by iwanbk** [comment]
```
@iwanbk Can't we do both? Check if the type is a string and if not, encode it as json?
```
Sure we can
