### ISSUE TITLE
Incorrect generation for builtin types

### ISSUE THREAD

**Issue by serboctor** [Jumpscale/go-raml#247]
When you specify a body type of a builtin type, the generated go functions call "Validate" on the body which is not implemented for the builtin types and causes an error.

**Example:**

          post:
            (AYSBased):
            displayName: CreateStoragePoolDevices
            description: Add extra devices to this storage pool
            body:
              application/json:
                description: List of devices to add to the storage pool
                type: string[]
                example: ['/dev/sdc', '/dev/sdd']

**Generated function:**

func (api NodeAPI) CreateStoragePoolDevices(w http.ResponseWriter, r *http.Request) {
	var reqBody []string

	// decode request
	if err := json.NewDecoder(r.Body).Decode(&reqBody); err != nil {
		w.WriteHeader(400)
		return
	}

	// validate request
	if err := reqBody.Validate(); err != nil {
		w.WriteHeader(400)
		w.Write([]byte(`{"error":"` + err.Error() + `"}`))
		return
	}
	// uncomment below line to add header
	// w.Header().Set("key","value")
}

**Comment by iwanbk** [comment]
@serboctor sorry for late response, was in vacation.

Fixed in #246.

test fixtures:
- https://github.com/Jumpscale/go-raml/blob/dbc7f7a0ca6dc681b4c9771a99c4a4c41c80ab74/codegen/fixtures/struct/validation.raml
- https://github.com/Jumpscale/go-raml/blob/dbc7f7a0ca6dc681b4c9771a99c4a4c41c80ab74/codegen/golang/fixtures/struct/validation/builtin_api.txt

@robvanmieghem it fixed in that PR/branch because it needs some fixes from that branch.
