### ISSUE TITLE
Generated Go code for array response is invalid

### ISSUE THREAD

**Issue by mohabusama** [Jumpscale/go-raml#31]
Hi

Assuming the following input raml file:

```YAML
#%RAML 1.0
title: UserApi
version: 0.1
baseUri: /users

types:
 user:
    properties:
        username:
            type: string
        email:
            type: string

    example:
        username: bob
        email:  bob@company.com

/users:

  get:
    description: Get all users
    responses:
        200:
            body:
                application/json:
                    type: user[]
```

the generated Go code for the `get` request handler:

```go
func(api UsersAPI) Get(w http.ResponseWriter, r *http.Request) {
	var respBody user[]
	json.NewEncoder(w).Encode(&respBody);

	// uncomment below line to add header
	// w.Header().Set("key","value")
}
```
`var respBody user[]` is invalid syntax.

Thanks,
Mohab

**Comment by iwanbk** [comment]
@mohabusama 
It is same as #24 by @zaibon , in that issue we conclude that we can't define new type in response body.
Let me know if you otherwise

**Comment by mohabusama** [comment]
I assumed this can be done via `inline type declarations` http://docs.raml.org/specs/1.0/#raml-10-spec-inline-type-declarations
but not sure what `... other than in a Type Expression.` really means here!

**Comment by iwanbk** [comment]
OK, i am not sure the right interpretation of the spec.
But it is not hard to implement.

I myself think it is OK to implement, @robvanmieghem ?

**Comment by robvanmieghem** [comment]
I think @mohabusama is right about the spec interpretation (I use that style as well and it is also generated like that by the Mulesoft API workbench).
It would be nice to have since the initial generation would not crash on the go fmt and it would immediately compile.
I  don't consider this high priority since it is in an implementing class, where the methods need to be filled in manually and it is not overwritten on regeneration.
