### ISSUE TITLE
Type of list of another type doesnt make sense in python/capnp

### ISSUE THREAD

**Issue by serboctor** [Jumpscale/go-raml#360]
If you generate a python client for the following raml, TypeofType class will generate fine and will have the attributes as Node (inheritance). However, in capnp, TypeofType will be an empty schema(https://github.com/Jumpscale/go-raml/issues/358)

```types:
  Node:
    type: object
    description: Node in the Zero-OS  0 Rest API
    properties:
      id: integer
      ipaddress: string

  TypeofType:
    type: Node
```
However, if you generate a client for the following raml, TypeofType will be an empty class that sets no attribute and doesn't refer to Node at all, because TypeofType doesn't really inherit from Node, it is simply a list of Nodes and it has no fields. 
So in a way, it doesn't make sense to have a class for it because unlike go where we can have `type TypeofType []Node`, python doesn't really have an equivalent. 
I am not sure how it can be handled. If we simply dont generate the class, this will break any types that refer to this type.
In capnp, the schema will also be empty for this case.

```
types:
  Node:
    type: object
    description: Node in the Zero-OS  0 Rest API
    properties:
      id: integer
      ipaddress: string

  TypeofType:
    type: Node[]
```

**Comment by serboctor** [comment]
The issue exists for any []type regardless of type being a user-defined type or a basic type.

**Comment by iwanbk** [comment]
> I am not sure how it can be handled. If we simply dont generate the class, this will break any types that refer to this type.

A possible solution is to create class template for a List.

```python
class ListOfNode:

    def __init__(self, json=None, **kwargs):
        self.elems = []
        arr = json or kwargs
        for data in arr:
            self.elems.append(Node(data))
.......
````

what do you think @serboctor @zaibon ?

**Comment by zaibon** [comment]
Could be a solution and this class should implement all the method of a list so it can be used as a normal list

**Comment by iwanbk** [comment]
I've tried to implement this class, basically the `ListOfNode` snippet above is working. It needs some modification though.

The obvious modification is it couldn't receive `**kwargs`.

The things i couldn't solve yet is how to implement `__str__` and `as_json` method, like the previous generated python class.
(Notes: we currently implement `__str__` by simply calling `as_json`

Python array can be encoded into JSON with `json.dumps` function. The problem is the array element, in this case is our generated python class.

I got this when tried to call `json.dumps` against `ListAnimal._elems`
```python
TypeError: <goramldir.Animal.Animal object at 0x7f88072daf28> is not JSON serializable
```

Calling `json.dumps` against `Animal` gave same error.

I think `json.dumps` against `ListAnimal._elems` is going to work once `json.dumps` works against our generated python class
