### ISSUE TITLE
python : import missing on type with raml keyword as it's name

### ISSUE THREAD

**Issue by lafont-e** [Jumpscale/go-raml#454]
When creating the client and server files for a raml file, (we work with github.com/zero-os/0-metadata/api_spec/main.raml file) two imports are missing on the client and server definition types.

The import missing is the one that references a field named "file" (yes a reserved word in python), can be seen generating the files associated with the raml and looking at the dir.py file in both client/ and server/types/ directories

We solved it adding a line to both files
    from .file import file as file_type
but those files are deleted each time we regenerate the raml, so the generator should deal with this case.

**Comment by iwanbk** [comment]
>  a field named "file" (yes a reserved work in python)

Is it not possible to change the type name to `File`? 
AFAIK, `File` is more pythonic than `file`.
see https://www.python.org/dev/peps/pep-0008/#class-names

But yeah, it is a valid bug.

Still, i suggest you to change it to `File` because:
- it is more pythonic, like mentioned above
- one of the go-raml developer is on vacation, so my PR won't get quick review, see https://github.com/Jumpscale/go-raml/pull/451 as example

**Comment by iwanbk** [comment]
after some checking, the issue is not because `file` is reserved python keyword.
but because `file` is a RAML scalar type https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#file
